// src/config/permissionConfig.js
export const permissionConfig = {
  roles: {
    admin: {
      name: 'Administrator',
      permissions: [
        'admin.access',
        'consultation.view',
        'consultation.create',
        'consultation.edit',
        'consultation.delete',
        'forms.view',
        'forms.create',
        'forms.edit',
        'forms.delete',
        'prescriptions.view',
        'prescriptions.create',
        'prescriptions.edit',
        'prescriptions.delete',
        'templates.view',
        'templates.create',
        'templates.edit',
        'templates.delete',
        'rules.view',
        'rules.manage',
        'workflows.view',
        'workflows.manage',
        'patients.view',
        'patients.create',
        'patients.edit',
        'patients.delete',
      ],
    },
    doctor: {
      name: 'Doctor',
      permissions: [
        'consultation.view',
        'consultation.create',
        'consultation.edit',
        'prescriptions.view',
        'prescriptions.create',
        'prescriptions.edit',
        'forms.view',
        'templates.view',
        'patients.view',
        'patients.create',
        'patients.edit',
        'templates.create',
        'templates.edit',
        'templates.delete',
        'forms.create',
        'forms.edit',
      ],
    },
    nurse: {
      name: 'Nurse',
      permissions: [
        'consultation.view',
        'consultation.create',
        'forms.view',
        'patients.view',
        'patients.create',
        'patients.edit',
      ],
    },
    receptionist: {
      name: 'Receptionist',
      permissions: [
        'patients.view',
        'patients.create',
        'patients.edit',
        'consultation.view',
      ],
    },
  },
  // Permission descriptions for documentation
  permissionDescriptions: {
    'admin.access': 'Access to admin panel',
    'consultation.view': 'View patient consultations',
    'consultation.create': 'Create new consultations',
    'consultation.edit': 'Edit existing consultations',
    'consultation.delete': 'Delete consultations',
    'forms.view': 'View forms',
    'forms.create': 'Create new forms',
    'forms.edit': 'Edit forms',
    'forms.delete': 'Delete forms',
    'prescriptions.view': 'View prescriptions',
    'prescriptions.create': 'Create prescriptions',
    'prescriptions.edit': 'Edit prescriptions',
    'prescriptions.delete': 'Delete prescriptions',
    'templates.view': 'View templates',
    'templates.create': 'Create templates',
    'templates.edit': 'Edit templates',
    'templates.delete': 'Delete templates',
    'rules.view': 'View business rules',
    'rules.manage': 'Manage business rules',
    'workflows.view': 'View workflows',
    'workflows.manage': 'Manage workflows',
    'patients.view': 'View patient records',
    'patients.create': 'Register new patients',
    'patients.edit': 'Edit patient records',
    'patients.delete': 'Delete patient records',
  },
};